[package]
name = "rustpwman"
version = "1.2.8"
authors = ["Martin <rmsk2@gmx.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10"
sha2 = "0.10"
md-5 = "0.10"
# Comment this line for Windows build
cursive = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11.7"
aes-gcm = "0.10"
cipher = "0.4"
aes = "0.8"
aead = "0.5"
base64 = "0.13"
rand = "0.8.5"
scrypt = "0.11"
clap = "4.0"
rpassword = "7.0"
argon2 = "0.4"
toml = "0.5.9"
dirs = "4.0"
uds_windows =  {version ="1.0.2", optional = true}
users = {version = "0.11.0", optional = true}

# Uncomment the following lines for Windows build
#pancurses = "0.17.0"
#pdcurses-sys = "0.7.1"

#[dependencies.cursive]
#version = "0.20"
#default-features = false
#features = ["pancurses-backend"]

[features]
# Use "pwmanclientwin" for Windowsbuild
default = ["pwmanclientux"]
pwmanclient = []
pwmanclientux = ["dep:users", "pwmanclient"]
pwmanclientwin = ["dep:uds_windows", "pwmanclient"]