[package]
name = "rustpwman"
version = "1.2.0"
authors = ["Martin <rmsk2@gmx.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
# Comment this line for Windows build
cursive = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11.7"
aes-gcm = "0.10.1"
cipher = "0.4"
aes = "0.8"
aead = "0.5"
base64 = "0.13"
rand = "0.8.5"
scrypt = "0.10.0"
clap = "4.0"
rpassword = "7.0"
argon2 = "0.4.1"
toml = "0.5.9"
dirs = "4.0"
users = {version = "0.11.0", optional = true}
hex = {version = "0.4.3", optional = true}

[features]
pwmanclient = ["dep:hex", "dep:users"]

# Uncomment the following lines for Windows build
#pancurses = "0.17.0"
#pdcurses-sys = "0.7.1"

#[dependencies.cursive]
#version = "0.20"
#default-features = false
#features = ["pancurses-backend"]