[package]
name = "rustpwman"
version = "0.1.0"
authors = ["Martin <rmsk2@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
cursive = "0.16.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11.5"
aes-gcm = "0.9.2"
cipher = "0.3.0"
aes = "0.7.4"
base64 = "0.13.0"
rand = "0.8.3"
scrypt = "0.7.0"